# Generated by Django 6.0.2 on 2026-02-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='course.coursecategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی نگاره',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای نگاره',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('instructor', models.CharField(max_length=255, verbose_name='استاد / مدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('short_desc', models.CharField(blank=True, max_length=500, verbose_name='توضیح کوتاه')),
                ('cover_image', models.ImageField(blank=True, upload_to='courses/covers/', verbose_name='تصویر کاور')),
                ('intro_video_url', models.URLField(blank=True, verbose_name='لینک ویدیو معرفی')),
                ('access_type', models.CharField(choices=[('free', 'رایگان'), ('paid', 'پولی'), ('premium', 'اشتراکی')], default='free', max_length=20, verbose_name='نوع دسترسی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('all', 'همه سطوح')], default='all', max_length=20, verbose_name='سطح دوره')),
                ('total_duration', models.PositiveIntegerField(default=0, verbose_name='مدت کل (دقیقه)')),
                ('lessons_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد درس')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='دارای گواهینامه')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('enrollments', models.PositiveIntegerField(default=0, verbose_name='ثبت\u200cنام')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='امتیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.coursecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'نگاره (دوره ویدیویی)',
                'verbose_name_plural': 'نگاره\u200cها (دوره\u200cهای ویدیویی)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان بخش')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'بخش دوره',
                'verbose_name_plural': 'بخش\u200cهای دوره',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درس')),
                ('lesson_type', models.CharField(choices=[('video', 'ویدیو'), ('audio', 'صوت'), ('pdf', 'PDF'), ('text', 'متن'), ('quiz', 'آزمون')], default='video', max_length=10, verbose_name='نوع محتوا')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدیو')),
                ('video_file', models.FileField(blank=True, upload_to='courses/videos/', verbose_name='فایل ویدیو')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='مدت زمان (ثانیه)')),
                ('is_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش رایگان')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.coursesection', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['order'],
            },
        ),
    ]
