# Generated by Django 6.0.2 on 2026-02-21 12:23

import django.db.models.deletion
import purchase.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('book', 'کتاب'), ('podcast', 'پادکست'), ('course', 'دوره ویدیویی')], max_length=10, verbose_name='نوع محتوا')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه محتوا')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('ref_id', models.CharField(default=purchase.models._ref, max_length=32, unique=True, verbose_name='شماره سفارش')),
                ('authority', models.CharField(blank=True, max_length=64, verbose_name='Authority زرین\u200cپال')),
                ('zp_ref_id', models.CharField(blank=True, max_length=64, verbose_name='RefID زرین\u200cپال (نهایی)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refunded', 'بازگشت وجه')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type', 'object_id'], name='purchase_pu_user_id_bda1dc_idx'), models.Index(fields=['authority'], name='purchase_pu_authori_2bcc9f_idx')],
            },
        ),
    ]
