# Generated by Django 6.0.2 on 2026-02-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='podcast.podcastcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پادکست',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پادکست',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PodcastSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مجموعه')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('host', models.CharField(max_length=255, verbose_name='گوینده / استاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, upload_to='podcasts/covers/', verbose_name='تصویر کاور')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='podcast.podcastcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مجموعه پادکست',
                'verbose_name_plural': 'مجموعه\u200cهای پادکست',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان قسمت')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='گوینده / استاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, upload_to='podcasts/covers/', verbose_name='تصویر کاور')),
                ('audio_file', models.FileField(blank=True, upload_to='podcasts/audio/', verbose_name='فایل صوتی')),
                ('audio_url', models.URLField(blank=True, verbose_name='لینک خارجی صوت (CDN)')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='مدت زمان (ثانیه)')),
                ('access_type', models.CharField(choices=[('free', 'رایگان'), ('paid', 'پولی'), ('premium', 'اشتراکی')], default='free', max_length=20, verbose_name='نوع دسترسی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('episode_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره قسمت')),
                ('plays', models.PositiveIntegerField(default=0, verbose_name='تعداد پخش')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='دانلود')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='امتیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='podcast.podcastcategory', verbose_name='دسته\u200cبندی')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='podcast.podcastseries', verbose_name='مجموعه')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست\u200cها',
                'ordering': ['series', 'episode_number', '-created_at'],
            },
        ),
    ]
