# Generated by Django 6.0.2 on 2026-02-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام بنر')),
                ('image', models.ImageField(upload_to='settings/banners/', verbose_name='تصویر بنر')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('position', models.CharField(choices=[('sidebar', 'سایدبار'), ('home_bottom', 'پایین صفحه اصلی'), ('in_content', 'داخل محتوا'), ('popup', 'پاپ\u200cآپ')], max_length=20, verbose_name='موقعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع نمایش')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان نمایش')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='سامانه جامع محبوب', max_length=100, verbose_name='نام سایت')),
                ('site_description', models.TextField(blank=True, verbose_name='توضیح کوتاه سایت (SEO)')),
                ('logo', models.ImageField(blank=True, upload_to='settings/logo/', verbose_name='لوگو اصلی')),
                ('logo_dark', models.ImageField(blank=True, upload_to='settings/logo/', verbose_name='لوگو حالت تاریک')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/favicon/', verbose_name='Favicon')),
                ('font_primary', models.CharField(choices=[('Vazirmatn', 'وزیر متن'), ('IranSans', 'ایران سنس'), ('Shabnam', 'شبنم'), ('Samim', 'صمیم'), ('custom', 'فونت سفارشی')], default='Vazirmatn', max_length=50, verbose_name='فونت اصلی')),
                ('font_custom_url', models.URLField(blank=True, verbose_name='لینک فونت سفارشی (Google / CDN)')),
                ('color_primary', models.CharField(default='#f65b5b', max_length=7, verbose_name='رنگ اصلی (HEX)')),
                ('color_secondary', models.CharField(default='#ff8c42', max_length=7, verbose_name='رنگ ثانویه (HEX)')),
                ('color_accent', models.CharField(default='#4a90d9', max_length=7, verbose_name='رنگ تاکید (HEX)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('telegram', models.URLField(blank=True, verbose_name='لینک تلگرام')),
                ('instagram', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='شماره واتساپ')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='کلمات کلیدی SEO')),
                ('google_analytics_id', models.CharField(blank=True, max_length=30, verbose_name='Google Analytics ID')),
                ('head_scripts', models.TextField(blank=True, verbose_name='اسکریپت\u200cهای <head>')),
                ('footer_scripts', models.TextField(blank=True, verbose_name='اسکریپت\u200cهای انتهای <body>')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='حالت تعمیر و نگهداری')),
                ('maintenance_message', models.TextField(blank=True, default='سایت در حال به\u200cروزرسانی است. لطفاً کمی بعد مراجعه کنید.', verbose_name='پیام تعمیر')),
                ('ai_welcome_popup', models.BooleanField(default=True, verbose_name='نمایش پاپ\u200cآپ هوش مصنوعی')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن فوتر')),
                ('copyright_text', models.CharField(blank=True, max_length=255, verbose_name='متن کپی\u200cرایت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام اسلایدر')),
                ('position', models.CharField(choices=[('home_top', 'صفحه اصلی — بالا'), ('home_middle', 'صفحه اصلی — میانی'), ('books', 'صفحه کتاب\u200cها'), ('courses', 'صفحه نگاره\u200cها')], default='home_top', max_length=20, verbose_name='محل نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('auto_play', models.BooleanField(default=True, verbose_name='پخش خودکار')),
                ('interval', models.PositiveSmallIntegerField(default=4000, verbose_name='فاصله پخش (ms)')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='عنوان آیتم')),
                ('url', models.CharField(max_length=200, verbose_name='لینک / URL')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون Font Awesome')),
                ('location', models.CharField(choices=[('header', 'هدر / منوی کشویی'), ('footer', 'فوتر'), ('bottom', 'نوار پایین (موبایل)')], default='header', max_length=10, verbose_name='محل نمایش')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='باز در تب جدید')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.menuitem', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['location', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان اسلاید')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='settings/sliders/', verbose_name='تصویر')),
                ('mobile_image', models.ImageField(blank=True, upload_to='settings/sliders/mobile/', verbose_name='تصویر موبایل')),
                ('link', models.URLField(blank=True, verbose_name='لینک اسلاید')),
                ('link_text', models.CharField(blank=True, max_length=50, verbose_name='متن دکمه')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='main.slider', verbose_name='اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
                'ordering': ['order'],
            },
        ),
    ]
