# Generated by Django 6.0.2 on 2026-02-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='baleh',
            field=models.CharField(blank=True, max_length=20, verbose_name='لینک بله'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='eitaa',
            field=models.CharField(blank=True, max_length=20, verbose_name='لینک ایتا'),
        ),
    ]
