# Generated by Django 6.0.2 on 2026-02-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesettings_baleh_sitesettings_eitaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='baleh',
            new_name='bale',
        ),
    ]
