# Generated by Django 6.0.2 on 2026-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_baleh_sitesettings_bale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='font_primary',
            field=models.CharField(choices=[('Vazirmatn', 'وزیر متن'), ('Shabnam', 'شبنم'), ('Samim', 'صمیم')], default='Vazirmatn', max_length=50, verbose_name='فونت اصلی'),
        ),
    ]
