# Generated by Django 6.0.2 on 2026-02-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faq_guidecategory_guidearticle_supportticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='fullname',
            field=models.CharField(default='', max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
    ]
