# Generated by Django 6.0.2 on 2026-02-20 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون (Font Awesome)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='book.bookcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی کتاب',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای کتاب',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کتاب')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('author', models.CharField(max_length=255, verbose_name='نویسنده / مولف')),
                ('translator', models.CharField(blank=True, max_length=255, verbose_name='مترجم')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='ناشر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات / معرفی کتاب')),
                ('cover_image', models.ImageField(blank=True, upload_to='books/covers/', verbose_name='تصویر جلد')),
                ('access_type', models.CharField(choices=[('free', 'رایگان'), ('paid', 'پولی'), ('premium', 'اشتراکی (ویژه اعضا)')], default='free', max_length=20, verbose_name='نوع دسترسی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('volume', models.PositiveSmallIntegerField(default=1, verbose_name='جلد / قسمت')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='شابک (ISBN)')),
                ('language', models.CharField(default='فارسی', max_length=30, verbose_name='زبان')),
                ('publish_year', models.CharField(blank=True, max_length=10, verbose_name='سال انتشار')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='امتیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه / پیشنهادی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='book.bookcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فصل')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب فصل')),
                ('is_preview', models.BooleanField(default=False, help_text='اگر فعال باشد، صفحات این فصل برای همه کاربران (بدون خرید) قابل خواندن است.', verbose_name='پیش\u200cنمایش رایگان')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'فصل کتاب',
                'verbose_name_plural': 'فصل\u200cهای کتاب',
                'ordering': ['order'],
                'unique_together': {('book', 'order')},
            },
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(help_text='شماره\u200cای که در کتاب اصلی است، مثلاً ۱، ۲ یا i، ii برای مقدمه', max_length=10, verbose_name='شماره صفحه (چاپی)')),
                ('order', models.PositiveIntegerField(db_index=True, help_text='ترتیب واقعی صفحه در سیستم — برای ناوبری قبلی/بعدی استفاده می\u200cشود', verbose_name='ترتیب نمایش')),
                ('content', models.TextField(help_text='متن کامل این صفحه. HTML ساده مجاز است.', verbose_name='متن صفحه')),
                ('heading', models.CharField(blank=True, help_text='اگر این صفحه شروع یک مبحث جدید است، عنوان آن را وارد کنید.', max_length=255, verbose_name='عنوان میانی')),
                ('page_image', models.ImageField(blank=True, help_text='اختیاری — مثلاً اسکن صفحه اصلی یا تصویر مرتبط', upload_to='books/pages/', verbose_name='تصویر صفحه')),
                ('editor_note', models.TextField(blank=True, help_text='داخلی — برای کاربر نمایش داده نمی\u200cشود.', verbose_name='یادداشت ویراستار')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='book.book', verbose_name='کتاب')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='book.bookchapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'صفحه کتاب',
                'verbose_name_plural': 'صفحات کتاب',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['book', 'order'], name='book_bookpa_book_id_92bf0a_idx'), models.Index(fields=['book', 'chapter'], name='book_bookpa_book_id_c8681f_idx')],
                'unique_together': {('book', 'order')},
            },
        ),
    ]
